# Generated by Django 6.0.2 on 2026-02-19 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='E.164 format, e.g. +15551234567', max_length=20)),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('preferred_channel', models.CharField(choices=[('BOTH', 'SMS + Email'), ('SMS', 'SMS Only'), ('EMAIL', 'Email Only')], default='BOTH', max_length=5)),
                ('daily_send_hour', models.PositiveSmallIntegerField(default=8, help_text='Hour (0-23) in user timezone to send daily tasks')),
                ('is_onboarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
