# Generated by Django 6.0.2 on 2026-02-19 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='30-Day Launch Plan', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('REPLACED', 'Replaced by new plan')], default='ACTIVE', max_length=10)),
                ('phase', models.PositiveSmallIntegerField(default=1)),
                ('duration_days', models.PositiveSmallIntegerField(default=30)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('ai_generation_metadata', models.JSONField(blank=True, default=dict, help_text='Model, prompt tokens, generation params')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_plans', to='onboarding.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('LEGAL', 'Legal & Registration'), ('FINANCE', 'Finance & Accounting'), ('MARKETING', 'Marketing & Branding'), ('PRODUCT', 'Product & Service'), ('SALES', 'Sales & Customers'), ('OPERATIONS', 'Operations & Setup'), ('DIGITAL', 'Digital Presence'), ('PLANNING', 'Strategy & Planning')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy (< 30 min)'), ('MEDIUM', 'Medium (30-90 min)'), ('HARD', 'Hard (2+ hours)')], default='MEDIUM', max_length=10)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=30)),
                ('day_number', models.PositiveSmallIntegerField(help_text='Which day in the plan (1-30) this task is scheduled for')),
                ('due_date', models.DateField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent to user'), ('DONE', 'Completed'), ('SKIPPED', 'Skipped'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('user_response', models.TextField(blank=True)),
                ('rescheduled_to', models.DateField(blank=True, null=True)),
                ('personalized_message', models.TextField(blank=True, help_text='AI-generated motivational message sent with this task')),
                ('ai_notes', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.taskplan')),
            ],
            options={
                'ordering': ['due_date', 'sort_order'],
            },
        ),
    ]
