# Generated by Django 6.0.2 on 2026-02-21 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('TEMPLATE', 'Template'), ('CHECKLIST', 'Checklist'), ('GUIDE', 'Reference Guide'), ('LINK', 'External Link'), ('WORKSHEET', 'Worksheet')], max_length=10)),
                ('content', models.TextField(blank=True, help_text='Template/guide/checklist content (markdown)')),
                ('external_url', models.URLField(blank=True)),
                ('business_types', models.JSONField(blank=True, default=list, help_text='Business types this applies to, e.g. ["bakery", "restaurant"]')),
                ('categories', models.JSONField(blank=True, default=list, help_text='Task categories: ["LEGAL", "MARKETING"]')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Freeform tags for search: ["llc", "texas"]')),
                ('status', models.CharField(choices=[('DRAFT', 'AI-Generated Draft'), ('REVIEWED', 'Reviewed & Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-times_used', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('TEMPLATE', 'Template'), ('CHECKLIST', 'Checklist'), ('GUIDE', 'Reference Guide'), ('LINK', 'External Link'), ('WORKSHEET', 'Worksheet')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tasks.task')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='tasks.resourcetemplate')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
