# Generated by Django 6.0.2 on 2026-02-22 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_resourcetemplate_taskresource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(choices=[('FIRST_TASK', 'First Task Completed'), ('FIRST_WEEK', 'First Week Complete'), ('STREAK_3', '3-Day Streak'), ('STREAK_7', '7-Day Streak'), ('STREAK_14', '14-Day Streak'), ('STREAK_30', '30-Day Streak'), ('HALF_PLAN', 'Halfway Through Plan'), ('PLAN_COMPLETE', 'Plan Completed'), ('CATEGORY_MASTER', 'Category Master'), ('SPEED_DEMON', 'Speed Demon'), ('COMEBACK', 'Comeback Kid'), ('MULTI_PLAN', 'Multi-Plan Veteran')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='StreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasks_completed', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
