# Generated by Django 6.0.2 on 2026-02-22 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_achievement_and_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskplan',
            name='previous_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_plans', to='tasks.taskplan'),
        ),
    ]
