# Generated by Django 6.0.2 on 2026-02-19 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(help_text='e.g. E-commerce, Consulting, Restaurant, SaaS', max_length=100)),
                ('stage', models.CharField(choices=[('IDEA', 'Just an Idea'), ('PLANNING', 'Planning Stage'), ('EARLY', 'Early Stage (0-6 months)'), ('GROWING', 'Growing (6-24 months)'), ('ESTABLISHED', 'Established (2+ years)')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Brief description of the business idea')),
                ('goals', models.JSONField(default=list, help_text='List of primary goals')),
                ('target_audience', models.TextField(blank=True)),
                ('budget_range', models.CharField(choices=[('BOOTSTRAP', '$0 - Bootstrap'), ('LOW', '$1 - $1,000'), ('MEDIUM', '$1,000 - $10,000'), ('HIGH', '$10,000+')], default='BOOTSTRAP', max_length=20)),
                ('location', models.CharField(blank=True, help_text='City/state or "Online only"', max_length=255)),
                ('ai_assessment', models.JSONField(blank=True, default=dict, help_text='Claude-generated business assessment JSON')),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('assessment_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Token usage, model info, step number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
