# Generated by Django 6.0.2 on 2026-02-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_experience',
            field=models.CharField(choices=[('NONE', 'No business experience'), ('SOME', 'Some experience (side projects, freelance)'), ('EXPERIENCED', 'Experienced (ran a business before)'), ('SERIAL', 'Serial entrepreneur')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_model',
            field=models.CharField(choices=[('PRODUCT', 'Physical/Digital Products'), ('SERVICE', 'Services'), ('SUBSCRIPTION', 'Subscription/Membership'), ('MARKETPLACE', 'Marketplace/Platform'), ('HYBRID', 'Hybrid/Multiple')], default='PRODUCT', max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='education_background',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='has_branding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='has_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='has_email_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='has_social_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='has_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='hours_per_day',
            field=models.PositiveSmallIntegerField(default=2, help_text='Hours available per day (1-8)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='known_competitors',
            field=models.JSONField(blank=True, default=list, help_text='Competitor names they already know'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='niche',
            field=models.CharField(blank=True, help_text='Specific sub-niche, e.g. "vegan bakery", "B2B SaaS"', max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skill keys from SKILL_CHOICES'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='social_platforms',
            field=models.JSONField(blank=True, default=list, help_text='Platform keys from PLATFORM_CHOICES'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='unique_selling_point',
            field=models.TextField(blank=True, help_text='What makes this business different'),
        ),
    ]
