# Generated by Django 6.0.2 on 2026-02-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_businessprofile_business_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='biggest_challenges',
            field=models.TextField(blank=True, default='', help_text='Current challenges (for existing businesses)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='current_revenue',
            field=models.CharField(blank=True, default='', help_text='Revenue bracket for existing businesses', max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='team_size',
            field=models.CharField(blank=True, default='', help_text='Team size for growing/established businesses', max_length=20),
        ),
    ]
