# Generated by Django 6.0.2 on 2026-02-22 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_businessprofile_biggest_challenges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_of', models.DateField(help_text='Monday of the week')),
                ('revenue_this_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_customers', models.PositiveSmallIntegerField(default=0)),
                ('hours_worked', models.PositiveSmallIntegerField(default=0)),
                ('energy_level', models.PositiveSmallIntegerField(choices=[(1, 'Exhausted'), (2, 'Low energy'), (3, 'Normal'), (4, 'Energized'), (5, 'On fire')], default=3)),
                ('biggest_win', models.TextField(blank=True)),
                ('biggest_blocker', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_pulses', to='onboarding.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_pulses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_of'],
                'unique_together': {('user', 'week_of')},
            },
        ),
    ]
