# Generated by Django 6.0.2 on 2026-02-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_weekly_pulse'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('CHAT', 'Chat')], default='SYSTEM', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
    ]
