# Generated by Django 6.0.2 on 2026-02-22 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_conversation_chat_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('SOCIAL_POST', 'Social Media Post'), ('EMAIL_CAMPAIGN', 'Email Campaign'), ('BIZ_PLAN_OUTLINE', 'Business Plan Outline'), ('ELEVATOR_PITCH', 'Elevator Pitch'), ('PRODUCT_DESCRIPTION', 'Product Description'), ('JOB_POSTING', 'Job Posting'), ('CUSTOMER_EMAIL', 'Customer Email'), ('AD_COPY', 'Ad Copy'), ('BLOG_POST', 'Blog Post Outline')], max_length=20)),
                ('platform', models.CharField(blank=True, choices=[('', 'General'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'X / Twitter'), ('tiktok', 'TikTok'), ('email', 'Email')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('prompt_used', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='onboarding.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
